### ISSUE TITLE
Even on unregistering, I'm getting LOGs from this API

### ISSUE THREAD

**Issue by jayesh83** [fatih-iver/touchy#2]
On unregistering, I'm still getting logs from this API. Ofcourse after unregister not getting events in broadcast but getting logs.

**Comment by fatih-iver** [comment]
Those logs are printed only for information & debug purposes @jayesh83.

**Comment by jayesh83** [comment]
Oh okay then. Got your point. I'll be closing this issue right away. Thank you for your time Fatih
